name: CI
on: 
  push:

env:
  PYTHONUNBUFFERED: 1
  FORCE_COLOR: 1
  CLICOLOR_FORCE: 1

concurrency:
  group: ci
  cancel-in-progress: true

jobs:
  
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.11"
          cache: pip
      - run: pipx install hatch
      - run: hatch run lint:all

  test:
    needs: lint
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ['3.11', '3.8']
    steps:
      - uses: actions/checkout@v3
      - run: pipx install hatch
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: pip
      - name: Test
        run: >
          hatch run test 
          notebooks/ws-pytext-pt01-intro.ipynb
          notebooks/ws-pytext-pt02-uebung-grundlagen.ipynb
          notebooks/ws-pytext-pt03a-nltk-intro.ipynb
          notebooks/ws-pytext-pt07-outro.ipynb
