name: Tests
on: [push]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - run: |
          pip install --upgrade black isort nbqa
      - run: |
          nbqa isort notebooks/*.ipynb
          nbqa black notebooks/*.ipynb
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ['3.10', '3.9', '3.8']
    steps:
      - uses: actions/checkout@v2
      - name: Install Python 3
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          pip install poetry
          poetry install
          python -V
          poetry -V
          poetry show
      - name: Test
        run: >
          poetry run pytest --nbval-lax 
          notebooks/ws-pytext-pt01-intro.ipynb
          notebooks/ws-pytext-pt02-uebung-grundlagen.ipynb
          notebooks/ws-pytext-pt03a-nltk-intro.ipynb
          notebooks/ws-pytext-pt07-outro.ipynb
